apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curl
        image: 799016889821.dkr.ecr.ap-northeast-2.amazonaws.com/curl:1.0.1
        command: ["/bin/sleep", "infinity"] 
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: kibana-config
          mountPath: /usr/share/kibana/config
      volumes:
      - name: kibana-config
        persistentVolumeClaim:
          claimName: kibana-config-pvc
---
